### ISSUE TITLE
2021.SIGIR.Group based Personalized Search by Integrating Search Behaviour and Friend Network

### ISSUE THREAD

**Issue by soroush-ziaeinejad** [fani-lab/community_prediction#16]
**Main problem:**
Document re-ranking and search personalization using multiple friend circles and individual search history. The method of this paper is called FNPS.

**Existing shortcomings:**

- Some of the existing methods highly rely on historical activities.
- Sometimes search history of a user is not enough or unavailable (So cannot be used)
- Considering users’ similarities, existing methods mostly consider just lexical or topical similarities which are simple and error-prone.

**Inputs:**

- User’s friend network (How?! It is not mentioned)
- Historical search behaviours (long-term and short-term)
- Current query

**Outputs:**

- **Individual Profile:** Applying an attention-based network on the combination of transformed short-term and long-term histories regarding the current query.
- **Group Profile:** Applying graph attention network on different friend circles to better capture the similarities.

**Two types of friend circles (to achieve group profile):**

- **Relation-based circles:** friends with the same background and experiences. Based on mutual friends
- **Behaviour-based circles:** friends with the same interests that are inferred from their search history. Same query or same click? You are connected!

Then these two types of circles are combined to form a group profile for each user based on three insights:

- Friends of a user are not equal in his/her friend circles.
- Importance of the friend who appears in both friend circles of the user
- Different weight for different friend circles based on the input query

**Personalization:**
Having individual and group profiles, returned documents for query q is scored based on the profiles and re-ranked according to their scores.

**Experiments:**

- **Dataset:** No public dataset for search logs and friendship information jointly. Dataset is collected from a social network (the name is not mentioned) that has an embedded search feature for 3 months in 2020. It contains: UID, query, timestamp, top 20 returned docs, clicks.
- **Metrics:** MAP, MRR, P@1, Avg. Clicks, NDCG@K

**Baselines:**

- **G-Click:** click-based grouping (click = desired document) / **WWW07**
- **DGF:** Topical similarity grouping (using LDA) / **SIGIR14**
- **PSSN:** Social explicit connections grouping / **CIKM09**
- **SonetRank:** Using social graph consisting of groups, users, queries, and clicks / **CIKM12**
- **HRNN:** Attention-based RNN / **CIKM18**
- **RPMN:** Memory networks / **WSDM20**
- **PEPS:** embedding of users’ historical activities / **SIGIR20**
- **HTPS:** Encoding history with context-aware representation / **SIGIR20**

**Code:**

The code for this project is provided [here](https://github.com/smallporridge/FNPS). It includes just the FNPS model and not the data.

**Presentation:**
The video presentation for this paper is available on [Video](https://underline.io/lecture/24740-group-based-personalized-search-by-integrating-search-behaviour-and-friend-network)

**Comment by hosseinfani** [comment]
Thanks. Very good summary. Is the code available?

**Comment by soroush-ziaeinejad** [comment]
@hosseinfani Please let me know if something is missing in my summary. Thanks.

**Comment by soroush-ziaeinejad** [comment]
Thanks Hossein. Yes, I found the code but it's just the implementation of the model. So, I updated the summary and added the 'Code' section.

**Comment by chrisyzw** [comment]
Thank you! But the video link does not work anymore. Is it still available?

**Comment by soroush-ziaeinejad** [comment]
> Thank you! But the video link does not work anymore. Is it still available?

Thank you for your interest in reading this summary. Yes, you are right. Unfortunately, the video is no longer available.
